Выполнил ДЗ по стримам
NaANic/hh-school-2022-java-collections-stream pull request #2
Opened 2022-12-20 07:17 UTC by NaANic

Task 1: сортировка с асимпто́тикой О(n)
Task 2 - 7: использование коллекций для решения задач
Task 8: оптимизировано с ориентиром на скорость работы и краткость

2022-12-21 18:31 UTC, genroelgvozo commented
больно общий комментарий по задаче 8, все таки хочется подробнее что именно не нравилось в коде и почему решил так поменять

2022-12-21 18:31 UTC, genroelgvozo requested changes

2022-12-21 18:31 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    Map<Integer, Person> personsInfo = persons.stream()
все норм, только название мапы странное какое-то, что за info?)

вроде personsMap вполне, или idPersonMap

2022-12-22 07:16 UTC, NaANic commented on src/main/java/tasks/Task1.java
> +    Map<Integer, Person> personsInfo = persons.stream()
idPersonMap  звучит красиво, сейчас исправлю ))) надеюсь personsInfo не сильно испортил впечатление в целом)))

2022-12-22 07:23 UTC, NaANic commented on src/main/java/tasks/Task8.java
/*

Удалена строка private long count;

Использовалась в методе countEven расширяя область видимости, больше нигде не использовалась, достаточно оставить ее локальной( p.s потом и вовсе удалим, достаточно стримов)

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +    return persons.stream()
/*
 
Удалена строка private long count;

Использовалась в методе countEven расширяя область видимости, больше нигде не использовалась, достаточно оставить ее локальной( p.s потом и вовсе удалим, достаточно стримов)

*/


/*

1. Убрал remove(0) - менять входящие переменные по логике метода не нужно

+ метод не будет выдавать разные результаты при повторном использовании

+ увеличивается время выполнения для перемещения элементов если ArrayList используется

+ в стриме легко читается

2. сollect(Collectors.toList()) заменил на просто toList() для краткости

3.  Убрал if - это избыточный код 

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +    return new HashSet<>(getNames(persons));
*
 
Set - уже коллекция уникальных элементов, distinct  не нужен, даже idea подсказывает

Конструктор   HashSet и так различные имена выдает(тоже idea подсказывает)

+ по времени на операции в stream не тратится время

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +            (person1, person2) -> person1));
/*

 Ушел от цикла к stream

+ компактнее код

+ меньше шансов ошибиться

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +        .collect(Collectors.joining(" "));
/*

Переименовал метод в convertPersonsFullNameToString, не сильно длинное название, зато абсолютно уверен что получишь по нему.

Вместо if'ов stream использовал

ушел баг с пробелом в начале строки, когда getSecondName() = null

меньше шансов ошибиться

короче код

такой stream хорошо читается и выглядит к месту

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +    return persons1.stream().anyMatch(new HashSet<>(persons2)::contains);
/*

+ меньше кода

+ В стримах читается легче

+ сложность O(n) вместо О( n^2) (не выполняется максимальное количество проверок)

disjoint  казалось короче, но если передавать для листа получится не так быстро

за счет памяти можно ускорить: 

если вторую коллекцию преобразовать в HashSet, тогда сложность будет не О(person1.size() * person2.size()), а О(person1.size() + person2.size())

person1.stream().anyMatch(new HashSet<>(person2)::contains)

*/

2022-12-23 05:11 UTC, NaANic commented on src/main/java/tasks/Task8.java
> +    return numbers.filter(number -> number % 2 == 0).count();
/*

Более логичным выглядит return numbers.filter(number -> number % 2 == 0).count();

убрал локальную переменную - Любая локальная переменная, формальный параметр или параметр исключения, использованный, но не объявленный в лямбда выражении, должен либо быть объявлен как final, либо быть effectively final, иначе при попытке его использования генерируется ошибка времени компиляции. ... Аналогичные правила использования переменных применяются в теле внутреннего класса  Ограничения на фактически финальные переменные запрещают доступ для динамического изменения локальных переменных, фиксация которых может привести к проблемам параллельности.

+ нет лишней переменной, вместо нее - метод count()

+ все в одной понятной конструкции

+ делает по умолчанию оптимально

+ сразу передается в return

*/

2022-12-23 05:31 UTC, genroelgvozo approved these changes

2022-12-23 08:02 UTC, merged